name = "filespy"
version = "0.5.0"

description = "Get notified of filesystem events in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "pta2002", repo = "gleam-filespy" }

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 2.0.0"
gleam_otp = "~> 0.10"
gleam_erlang = "~> 0.25"
fs = "~> 8.6"

[dev-dependencies]
gleeunit = "~> 1.0.2"
